### ISSUE TITLE
Videos in examples are not visible due to Unsecure URL source

### ISSUE THREAD

**Issue by danieltorrer** [linux-man/VLCJVideo#3]
The demos are using a URL from a webpage that has an insecure SSL cert, making videos to not play on the examples sketches. Not really an issue with the library itself but just a heads up about the examples.

For example `  video.openAndPlay("https://www.sample-videos.com/video123/mp4/360/big_buck_bunny_360p_30mb.mp4");` shows the error if I copy and open the url in firefox.

**Comment by linux-man** [comment]
Thank you. Don't know what and when it happened. I'll update the examples.

**Comment by linux-man** [comment]
Done with f769e39.
